// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aI_ZAQvuEwExpTO1zgUYn_yp1MNTkuo',
    appId: '1:170364614246:web:79b128f3183ebf18e21fa7',
    messagingSenderId: '170364614246',
    projectId: 'smart-cv-analysis',
    authDomain: 'smart-cv-analysis.firebaseapp.com',
    storageBucket: 'smart-cv-analysis.firebasestorage.app',
    measurementId: 'G-M26XC4F5W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsz5xVZYQazvYxAJS1tLboWGv9d8Q3XZY',
    appId: '1:170364614246:android:3d8e136dc8588c92e21fa7',
    messagingSenderId: '170364614246',
    projectId: 'smart-cv-analysis',
    storageBucket: 'smart-cv-analysis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tLRpeds-ZH6CE8UDOqYv2o74bFhZ5HY',
    appId: '1:170364614246:ios:04c9a71661178142e21fa7',
    messagingSenderId: '170364614246',
    projectId: 'smart-cv-analysis',
    storageBucket: 'smart-cv-analysis.firebasestorage.app',
    iosBundleId: 'com.example.smartCvAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2tLRpeds-ZH6CE8UDOqYv2o74bFhZ5HY',
    appId: '1:170364614246:ios:04c9a71661178142e21fa7',
    messagingSenderId: '170364614246',
    projectId: 'smart-cv-analysis',
    storageBucket: 'smart-cv-analysis.firebasestorage.app',
    iosBundleId: 'com.example.smartCvAnalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9aI_ZAQvuEwExpTO1zgUYn_yp1MNTkuo',
    appId: '1:170364614246:web:2b7db35ee21ec4a5e21fa7',
    messagingSenderId: '170364614246',
    projectId: 'smart-cv-analysis',
    authDomain: 'smart-cv-analysis.firebaseapp.com',
    storageBucket: 'smart-cv-analysis.firebasestorage.app',
    measurementId: 'G-C05L0FR6R2',
  );
}
